<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds with 35 comprehensive software showcase projects.
     */
    public function run(): void
    {
        $products = [
            // =========================================================================
            // 1. SAAS & CLOUD SYSTEMS (Web Apps)
            // =========================================================================
            [
                'title' => 'Invozen — Multi-Tenant Cloud Invoicing & Billing SaaS',
                'slug' => 'invozen-cloud-billing-saas',
                'type' => 'web_app',
                'category' => 'Fintech & SaaS',
                'price' => 799.00,
                'short_description' => 'Multi-tenant subscription billing engine with automated Stripe invoices, Reverb WebSocket updates, and PDF receipt exports.',
                'description' => 'Invozen is a high-performance billing microservice built for modern SaaS companies. It handles tax calculations, payment gateway webhooks, customer recurring subscriptions, and multi-currency billing out of the box with team role-based access.',
                'demo_url' => 'https://demo.invozen.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@invozen.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1200&q=80',
                'tech_stack' => ['Laravel 12', 'Next.js 15', 'Tailwind CSS', 'Stripe', 'PostgreSQL', 'Reverb WebSockets'],
                'features' => ['Multi-currency Stripe & SSLCommerz Checkout', 'Automated recurring billing cron schedules', 'Interactive invoice builder with PDF export', 'Real-time WebSocket payment notifications', 'Team seat management & audit logs'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'TaskFlow — Collaborative Agile Kanban & Sprint Suite',
                'slug' => 'taskflow-agile-kanban-suite',
                'type' => 'web_app',
                'category' => 'Productivity & Collaboration',
                'price' => 599.00,
                'short_description' => 'Real-time collaborative project management tool with drag-and-drop Kanban boards, sprint burn-down charts, and live team presence.',
                'description' => 'TaskFlow brings modern issue tracking, milestone management, and time logging into a fast, fluid interface. Powered by WebSockets, team members see live drag-and-drop updates, comments, and task assignments instantly without refreshing.',
                'demo_url' => 'https://demo.taskflow.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@taskflow.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=1200&q=80',
                'tech_stack' => ['React 19', 'Laravel 12', 'Tailwind CSS', 'Reverb WebSockets', 'Redis'],
                'features' => ['Live drag-and-drop Kanban card movements', 'Sprint burn-down & team velocity charts', 'Custom task custom fields & priority badges', 'Instant browser & email mention notifications'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'CloudDesk — Omnichannel Help Desk & Ticket Center',
                'slug' => 'clouddesk-omnichannel-helpdesk',
                'type' => 'web_app',
                'category' => 'Customer Support',
                'price' => 850.00,
                'short_description' => 'Unified customer support platform with live WebSocket chat, SLA tracking, email piping, and automated AI response suggestions.',
                'description' => 'Streamline your support operations across Email, Web Widget, and API tickets. Includes SLA timers, automated ticket routing, agent collision detection, and customizable satisfaction surveys.',
                'demo_url' => 'https://demo.clouddesk.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@clouddesk.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1556745757-8d76bdb6984b?w=1200&q=80',
                'tech_stack' => ['Next.js 15', 'Laravel 12', 'Reverb WebSockets', 'PostgreSQL', 'Tailwind CSS'],
                'features' => ['Live customer webchat widget', 'Automated SLA breach escalation rules', 'Shared team inboxes with internal notes', 'Comprehensive agent resolution analytics'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'PulseMetrics — Real-Time Server & Application Telemetry',
                'slug' => 'pulsemetrics-server-telemetry',
                'type' => 'web_app',
                'category' => 'DevOps & Monitoring',
                'price' => 1100.00,
                'short_description' => 'Lightweight server monitoring and uptime alerting platform with CPU/RAM metrics, SSL expiry notifications, and incident status pages.',
                'description' => 'PulseMetrics monitors your HTTP endpoints, server resources, database queries, and background queues. Publish branded public status pages and alert teams via Telegram, Slack, or SMS upon downtime.',
                'demo_url' => 'https://demo.pulsemetrics.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@pulsemetrics.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80',
                'tech_stack' => ['Laravel 12', 'Chart.js', 'Next.js 15', 'Redis TimeSeries', 'Docker'],
                'features' => ['Global multi-region HTTP ping probes', 'Branded public incident status pages', 'Telegram & Discord webhook alerts', 'SSL certificate expiration early warnings'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'MemberVault — Community & Paid Membership Platform',
                'slug' => 'membervault-paid-community-platform',
                'type' => 'web_app',
                'category' => 'Social & Community',
                'price' => 750.00,
                'short_description' => 'All-in-one community hub for creators, course sellers, and private networks with gated forums, video courses, and Stripe subscriptions.',
                'description' => 'Build and monetize your brand community. MemberVault combines video lessons, private discussion channels, live event streaming, and automated member tier access control.',
                'demo_url' => 'https://demo.membervault.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@membervault.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&q=80',
                'tech_stack' => ['Next.js 15', 'Laravel 12', 'Tailwind CSS', 'Stripe Billing', 'Vimeo API'],
                'features' => ['Gated video courses with progress tracking', 'Real-time discussion feed & community channels', 'Tiered subscription pricing plans', 'Member direct messaging with attachments'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'FormCraft — Dynamic Drag & Drop Form & Survey Builder',
                'slug' => 'formcraft-dynamic-form-builder',
                'type' => 'web_app',
                'category' => 'SaaS & Tools',
                'price' => 450.00,
                'short_description' => 'No-code dynamic form builder with conditional logic, payment collection fields, webhook dispatchers, and CSV exports.',
                'description' => 'Create complex multi-step forms, surveys, and quiz lead magnets in minutes. Features embedded widgets, response analytics, conditional field branching, and instant email notifications.',
                'demo_url' => 'https://demo.formcraft.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@formcraft.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
                'tech_stack' => ['React 19', 'Laravel 12', 'Tailwind CSS', 'MySQL', 'Alpine.js'],
                'features' => ['Visual drag-and-drop form canvas', 'Advanced conditional skip logic', 'Integrated Stripe payment field support', 'Custom webhook payloads for Zapier/Make'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'DocuSigner — Secure Digital Contract & E-Signature Suite',
                'slug' => 'docusigner-digital-contract-suite',
                'type' => 'web_app',
                'category' => 'Legal & Enterprise',
                'price' => 1200.00,
                'short_description' => 'Audit-compliant electronic signature platform with PDF field placement, automated reminder emails, and cryptographic verification.',
                'description' => 'Send contracts, NDAs, and agreements for signature. Includes full tamper-evident audit trails, signature certificates, multi-recipient routing orders, and cloud storage backup.',
                'demo_url' => 'https://demo.docusigner.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@docusigner.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1200&q=80',
                'tech_stack' => ['Laravel 12', 'Next.js 15', 'PDFtk', 'FPDF', 'Tailwind CSS'],
                'features' => ['Visual signature field drag-and-drop over PDF', 'Sequential and parallel multi-signer routing', 'Cryptographic SHA-256 tamper verification', 'Automated reminder emails & expiration dates'],
                'is_featured' => true,
                'is_active' => true,
            ],

            // =========================================================================
            // 2. MOBILE APPLICATIONS (Android APK & iOS TestFlight)
            // =========================================================================
            [
                'title' => 'FleetTrack — Real-time GPS & Delivery Logistics Mobile App',
                'slug' => 'fleettrack-logistics-mobile-app',
                'type' => 'android',
                'category' => 'Logistics & IoT',
                'price' => 1250.00,
                'short_description' => 'Cross-platform mobile application with live driver GPS tracking, background geolocation telemetry, and push notification dispatching.',
                'description' => 'Engineered for courier networks, on-demand delivery services, and transport fleets. Features live turn-by-turn routing, driver proof-of-delivery signatures, and instant FCM push alerts.',
                'demo_url' => 'https://demo.fleettrack.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@fleettrack.com',
                'admin_demo_password' => 'password123',
                'apk_url' => 'https://example.com/downloads/fleettrack-v2.1-release.apk',
                'thumbnail' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&q=80',
                'tech_stack' => ['Flutter 3.24', 'Laravel 12 REST API', 'Firebase FCM', 'Mapbox SDK', 'Redis Geolocation'],
                'features' => ['Real-time live map tracking via WebSockets', 'Digital signature & photo proof of delivery', 'Offline order caching with auto-sync', 'Android APK standalone build ready'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'FoodieExpress — On-Demand Food Delivery & Restaurant App',
                'slug' => 'foodieexpress-food-delivery-app',
                'type' => 'android',
                'category' => 'Food & Restaurant',
                'price' => 1450.00,
                'short_description' => 'Customer, Driver, and Restaurant 3-in-1 ecosystem with live order tracking, menu modifiers, and instant card payments.',
                'description' => 'A complete food delivery solution with customer ordering app, kitchen order management tablet dashboard, and driver routing navigation. Supports promo codes, loyalty points, and live order status broadcasts.',
                'demo_url' => 'https://demo.foodieexpress.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@foodie.com',
                'admin_demo_password' => 'password123',
                'apk_url' => 'https://example.com/downloads/foodie-v3.0.apk',
                'thumbnail' => 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=1200&q=80',
                'tech_stack' => ['Flutter', 'Laravel 12 API', 'Stripe', 'Google Maps SDK', 'Pusher/Reverb'],
                'features' => ['Live kitchen order preparation status', 'Driver GPS location updates on map', 'Multi-item menu modifiers & toppings', 'Instant refund and order cancellation flows'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'FitPulse — AI Workout Planner & Calorie Tracker App',
                'slug' => 'fitpulse-fitness-mobile-app',
                'type' => 'ios',
                'category' => 'Health & Fitness',
                'price' => 890.00,
                'short_description' => 'Personalized fitness app with animated exercise guides, calorie logging, Apple HealthKit sync, and subscription workouts.',
                'description' => 'FitPulse offers structured workout routines, interactive rep timers, macro meal logging, and Apple Watch companion features. Includes in-app subscriptions via Apple StoreKit and Google Play Billing.',
                'demo_url' => 'https://demo.fitpulse.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@fitpulse.com',
                'admin_demo_password' => 'password123',
                'testflight_url' => 'https://testflight.apple.com/join/demo-fitpulse',
                'thumbnail' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1200&q=80',
                'tech_stack' => ['React Native', 'Laravel 12 API', 'RevenueCat', 'Apple HealthKit', 'Tailwind CSS'],
                'features' => ['Animated 3D exercise movement guides', 'Macro calorie scanner with barcode lookup', 'Apple HealthKit & Google Fit integration', 'iOS TestFlight beta available'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'PayWave — Peer-to-Peer Mobile Wallet & QR Payments',
                'slug' => 'paywave-mobile-wallet-app',
                'type' => 'android',
                'category' => 'Fintech',
                'price' => 1650.00,
                'short_description' => 'Secure mobile banking & wallet app with QR merchant payments, instant P2P transfers, virtual cards, and biometric 2FA.',
                'description' => 'Designed with banking-grade security. Features QR code scanning for merchant checkout, instant money requests, virtual debit card generation, and transaction receipt downloads.',
                'demo_url' => 'https://demo.paywave.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@paywave.com',
                'admin_demo_password' => 'password123',
                'apk_url' => 'https://example.com/downloads/paywave-app.apk',
                'thumbnail' => 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=1200&q=80',
                'tech_stack' => ['Flutter 3.24', 'Laravel 12 Microservice', 'JWT Auth', 'Biometrics', 'Redis'],
                'features' => ['Instant P2P transfers by phone number or QR', 'Biometric fingerprint & Face ID login', 'Merchant QR payment scanner', 'Real-time SMS & push transaction alerts'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'RideGo — On-Demand Taxi & Ride Hailing Mobile Suite',
                'slug' => 'ridego-ride-hailing-mobile-suite',
                'type' => 'ios',
                'category' => 'Transportation & Mobility',
                'price' => 1800.00,
                'short_description' => 'Uber-like ride hailing application with live driver map matching, surge pricing algorithms, and in-app chat.',
                'description' => 'Complete mobility system with rider app, driver app, and central dispatch control tower. Includes fare calculation, promo codes, ride scheduling, and emergency SOS safety features.',
                'demo_url' => 'https://demo.ridego.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@ridego.com',
                'admin_demo_password' => 'password123',
                'testflight_url' => 'https://testflight.apple.com/join/demo-ridego',
                'thumbnail' => 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=1200&q=80',
                'tech_stack' => ['Flutter', 'Laravel 12', 'Reverb WebSockets', 'Google Maps API', 'Stripe'],
                'features' => ['Real-time vehicle movement on map', 'Dynamic surge pricing & fare estimation', 'In-app driver/rider VoIP & chat', 'iOS TestFlight ready for testing'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Medix — Telehealth & Virtual Doctor Consultation App',
                'slug' => 'medix-telehealth-consultation-app',
                'type' => 'android',
                'category' => 'Healthcare',
                'price' => 1350.00,
                'short_description' => 'Patient-doctor consultation app with WebRTC video calling, appointment booking, digital prescriptions, and health records.',
                'description' => 'Connect patients with licensed physicians. Features secure video consultations, prescription PDF downloads, laboratory report uploads, and doctor schedule management.',
                'demo_url' => 'https://demo.medix.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@medix.com',
                'admin_demo_password' => 'password123',
                'apk_url' => 'https://example.com/downloads/medix-health-v1.apk',
                'thumbnail' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&q=80',
                'tech_stack' => ['Flutter', 'WebRTC', 'Laravel 12 API', 'Twilio', 'PostgreSQL'],
                'features' => ['HD WebRTC 1-on-1 video consultations', 'Electronic prescription generation with signature', 'Patient medical history & file vault', 'Integrated appointment reminder notifications'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'CryptoVault — Multi-Chain Crypto Wallet & DeFi Tracker',
                'slug' => 'cryptovault-defi-wallet-app',
                'type' => 'ios',
                'category' => 'Web3 & Crypto',
                'price' => 1500.00,
                'short_description' => 'Non-custodial cryptocurrency wallet app supporting Ethereum, Solana, and Bitcoin with live portfolio charts and token swaps.',
                'description' => 'Safe, non-custodial crypto wallet. Features private key seed phrase encryption on-device, DEX token swaps, NFT gallery viewer, and live price alert push notifications.',
                'demo_url' => 'https://demo.cryptovault.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@cryptovault.com',
                'admin_demo_password' => 'password123',
                'testflight_url' => 'https://testflight.apple.com/join/demo-cryptovault',
                'thumbnail' => 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=1200&q=80',
                'tech_stack' => ['React Native', 'Ethers.js', 'Solana Web3', 'Laravel 12 API', 'Tailwind CSS'],
                'features' => ['On-device encrypted mnemonic seed vault', 'DEX swap routing via 1inch/Uniswap APIs', 'NFT collection showcase & metadata display', 'iOS TestFlight build ready'],
                'is_featured' => false,
                'is_active' => true,
            ],

            // =========================================================================
            // 3. E-COMMERCE & MARKETPLACES
            // =========================================================================
            [
                'title' => 'ShopZen — Headless High-Speed E-Commerce Platform',
                'slug' => 'shopzen-headless-ecommerce-platform',
                'type' => 'web_app',
                'category' => 'E-Commerce',
                'price' => 890.00,
                'short_description' => 'Blazing-fast headless e-commerce frontend in Next.js 15 with Laravel microservice backend, polymorphic media gallery, and Stripe checkout.',
                'description' => 'Engineered for conversion and high traffic. Features instant faceted search, inventory stock management, coupon codes, abandoned cart recovery emails, and guest checkout options.',
                'demo_url' => 'https://demo.shopzen.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@shopzen.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1557821552-17105176677c?w=1200&q=80',
                'tech_stack' => ['Next.js 15', 'Laravel 12', 'Tailwind CSS', 'Stripe Elements', 'Redis Cache'],
                'features' => ['Sub-second page load times with Next.js ISR', 'Polymorphic product gallery & video showcases', 'Multi-gateway checkout (Stripe, SSLCommerz, COD)', 'Automated abandoned cart email sequences'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'MarketHub — Multi-Vendor B2B & B2C Marketplace',
                'slug' => 'markethub-multivendor-marketplace',
                'type' => 'web_app',
                'category' => 'Marketplace',
                'price' => 1750.00,
                'short_description' => 'Complete multi-vendor marketplace with separate vendor portals, commission splitting, payout management, and product approval queues.',
                'description' => 'Allows thousands of independent vendors to open digital storefronts. Features automated commission deduction, vendor shipping profiles, product variation matrices, and customer review moderation.',
                'demo_url' => 'https://demo.markethub.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@markethub.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=1200&q=80',
                'tech_stack' => ['Laravel 12', 'Next.js 15', 'Tailwind CSS', 'Stripe Connect', 'MySQL'],
                'features' => ['Automated vendor commission payouts via Stripe Connect', 'Individual seller store URLs & custom branding', 'Bulk CSV product imports & exports', 'Customer-to-vendor direct inquiries'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'PropertyHub — Real Estate Portal & Agent CRM',
                'slug' => 'propertyhub-real-estate-portal',
                'type' => 'web_app',
                'category' => 'Real Estate',
                'price' => 1100.00,
                'short_description' => 'Real estate listing engine with interactive map search, virtual 3D tour embeds, agent lead capture, and mortgage calculators.',
                'description' => 'Showcase commercial and residential properties. Includes geolocation boundary searching, schedule a visit calendar booking, agent lead management, and automated property PDF brochures.',
                'demo_url' => 'https://demo.propertyhub.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@propertyhub.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80',
                'tech_stack' => ['Next.js 15', 'Laravel 12', 'Mapbox GL', 'Tailwind CSS', 'PostgreSQL'],
                'features' => ['Interactive map clustering with polygon search', 'Matterport 3D virtual tour embedding', 'Instant WhatsApp inquiry connection with agents', 'Schedule a viewing calendar integration'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'AutoBazaar — Vehicle Classifieds & Dealership Marketplace',
                'slug' => 'autobazaar-car-dealership-marketplace',
                'type' => 'web_app',
                'category' => 'Automotive',
                'price' => 980.00,
                'short_description' => 'Car buying and selling platform with VIN lookup, dealership inventory management, loan finance calculators, and test drive booking.',
                'description' => 'Designed for individual car sellers and certified dealerships. Features vehicle inspection report uploads, mileage and spec comparison tables, and direct lead generation to dealer CRM.',
                'demo_url' => 'https://demo.autobazaar.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@autobazaar.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=80',
                'tech_stack' => ['Laravel 12', 'React 19', 'Tailwind CSS', 'MySQL', 'Alpine.js'],
                'features' => ['Faceted filters (Make, Model, Year, Fuel, Mileage)', 'Side-by-side vehicle comparison matrix', 'Dealership inventory batch manager', 'Test drive scheduling calendar'],
                'is_featured' => false,
                'is_active' => true,
            ],

            // =========================================================================
            // 4. AI & MACHINE LEARNING PLATFORMS
            // =========================================================================
            [
                'title' => 'GeniusAI — Generative Copywriting & Content Studio',
                'slug' => 'geniusai-content-creation-studio',
                'type' => 'web_app',
                'category' => 'Artificial Intelligence',
                'price' => 850.00,
                'short_description' => 'AI SaaS workspace offering blog generation, social media captions, code writing, and image creation with credit token billing.',
                'description' => 'Integrate OpenAI, Claude, and Stable Diffusion models under one unified SaaS platform. Includes pre-built prompt templates, credit token usage tracking, and team workspace folders.',
                'demo_url' => 'https://demo.geniusai.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@geniusai.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&q=80',
                'tech_stack' => ['Next.js 15', 'Laravel 12 API', 'OpenAI API', 'Stripe Billing', 'Tailwind CSS'],
                'features' => ['60+ Ready-to-use AI copywriting templates', 'Streaming chat responses with markdown syntax highlighting', 'Credit token allocation and refill purchase flows', 'Export documents to Word, PDF, and Markdown'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'VisionOCR — Intelligent Invoice & Document Data Parser',
                'slug' => 'visionocr-document-parser-api',
                'type' => 'custom',
                'category' => 'AI & Microservices',
                'price' => 1400.00,
                'short_description' => 'AI-powered OCR microservice that extracts structured JSON data from PDF receipts, invoices, passports, and identity documents.',
                'description' => 'Eliminate manual data entry. Upload documents or send via REST API to receive clean, validated JSON schemas with confidence scores for line items, totals, dates, and vendor addresses.',
                'demo_url' => 'https://demo.visionocr.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@visionocr.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&q=80',
                'tech_stack' => ['Python FastAPI', 'Laravel 12 Gateway', 'Tesseract/OpenCV', 'Docker', 'PostgreSQL'],
                'features' => ['Automated tabular data & line item extraction', 'Confidence scores & anomaly detection flags', 'REST API key authentication & rate limiting', 'Direct accounting webhook sync (QuickBooks/Xero)'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'NeuroVoice — Real-time Speech-to-Text & Transcription AI',
                'slug' => 'neurovoice-speech-transcription-ai',
                'type' => 'web_app',
                'category' => 'Artificial Intelligence',
                'price' => 690.00,
                'short_description' => 'Audio transcription and meeting summary tool with speaker diarization, action item detection, and multi-language translation.',
                'description' => 'Upload MP3, WAV, or record live audio to generate timestamped transcripts with 98% accuracy. Automatically generates executive summaries and assigns action items to team members.',
                'demo_url' => 'https://demo.neurovoice.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@neurovoice.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=1200&q=80',
                'tech_stack' => ['Next.js 15', 'Whisper AI', 'Laravel 12 API', 'Tailwind CSS', 'FFmpeg'],
                'features' => ['Multi-speaker diarization with timestamps', 'Automated meeting minutes & action item bullet points', 'Export to SRT, VTT, PDF, and DOCX', '50+ Language translation support'],
                'is_featured' => false,
                'is_active' => true,
            ],

            // =========================================================================
            // 5. DEVELOPER TOOLS & MICROSERVICES
            // =========================================================================
            [
                'title' => 'WebHookRelay — Resilient Webhook Ingestion & Delivery Gateway',
                'slug' => 'webhookrelay-delivery-gateway',
                'type' => 'custom',
                'category' => 'Developer Tools',
                'price' => 650.00,
                'short_description' => 'Fault-tolerant webhook gateway with automatic exponential backoff retries, signature verification, and payload replay debugging.',
                'description' => 'Never lose a third-party webhook event again. Ingest millions of webhooks from Stripe, Shopify, GitHub, or PayPal, inspect headers, and replay failed deliveries with one click.',
                'demo_url' => 'https://demo.webhookrelay.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@webhookrelay.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&q=80',
                'tech_stack' => ['Laravel 12 Microservice', 'Redis Streams', 'Next.js 15 Dashboard', 'Docker', 'Reverb'],
                'features' => ['Sub-millisecond webhook ingestion & queuing', 'Automatic exponential backoff retry policies', 'Visual payload inspector with diff viewer', 'One-click delivery replay & endpoint testing'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'AuthGuard — Enterprise Identity & Single Sign-On (SSO) Engine',
                'slug' => 'authguard-sso-identity-engine',
                'type' => 'custom',
                'category' => 'Security & Auth',
                'price' => 1100.00,
                'short_description' => 'Centralized authentication server with OAuth2, OIDC, SAML2, Magic Link, OTP verification, and JWT session blacklists.',
                'description' => 'Unify user identities across multiple apps. Provides seamless Single Sign-On (SSO), social logins (Google, Apple, GitHub), enterprise SAML, and brute-force IP rate limiting.',
                'demo_url' => 'https://demo.authguard.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@authguard.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=1200&q=80',
                'tech_stack' => ['Laravel 12 Passport', 'Sanctum', 'Next.js 15', 'Redis Token Vault', 'Tailwind CSS'],
                'features' => ['OAuth2 & OpenID Connect provider endpoints', 'Passwordless Magic Link & SMS OTP login', 'JWT Token Blacklist and active session revoke', 'Audit logs with geo-IP location tracking'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'QueuePilot — Distributed Asynchronous Job Orchestrator',
                'slug' => 'queuepilot-distributed-job-orchestrator',
                'type' => 'custom',
                'category' => 'DevOps & Backend',
                'price' => 800.00,
                'short_description' => 'Real-time background worker monitoring dashboard for Redis queues, cron schedules, job failure alerts, and throughput graphs.',
                'description' => 'Gain complete visibility into your async job pipelines. Monitor queue latency, retry failed jobs in batches, schedule recurring tasks, and receive alerts before queues back up.',
                'demo_url' => 'https://demo.queuepilot.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@queuepilot.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=1200&q=80',
                'tech_stack' => ['Laravel Horizon', 'Laravel 12', 'Reverb WebSockets', 'Redis', 'Vue 3'],
                'features' => ['Live queue throughput and memory graphs', 'Batch retry and purge for failed jobs', 'Cron schedule visual timeline dashboard', 'Slack and email queue bottleneck alerts'],
                'is_featured' => false,
                'is_active' => true,
            ],

            // =========================================================================
            // 6. EDTECH & LEARNING SYSTEMS
            // =========================================================================
            [
                'title' => 'SkillStream — Video Course LMS & Online Academy',
                'slug' => 'skillstream-lms-online-academy',
                'type' => 'web_app',
                'category' => 'Education & EdTech',
                'price' => 950.00,
                'short_description' => 'Comprehensive Learning Management System with video streaming, lesson completion tracking, interactive quizzes, and certificates.',
                'description' => 'Sell video courses, live bootcamps, and digital certificates. Features student progress dashboards, instructor revenue splitting, downloadable resources, and interactive Q&A discussions.',
                'demo_url' => 'https://demo.skillstream.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@skillstream.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=1200&q=80',
                'tech_stack' => ['Next.js 15', 'Laravel 12 API', 'Tailwind CSS', 'Stripe', 'HLS Video Stream'],
                'features' => ['Video resume progress memory across devices', 'Automated PDF Certificate of Completion generator', 'Multi-instructor marketplace payouts', 'Interactive quiz assessments with pass/fail gates'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'QuizMaster — Real-Time Multiplayer Trivia & Exam Arena',
                'slug' => 'quizmaster-live-exam-arena',
                'type' => 'android',
                'category' => 'EdTech & Gaming',
                'price' => 700.00,
                'short_description' => 'Real-time multiplayer quiz game and competitive examination app with live WebSocket leaderboards and prize reward wallets.',
                'description' => 'Host live Kahoot-style quiz competitions or institutional timed exams. Features instant score broadcasting, negative marking rules, anti-cheating tab detection, and achievement badges.',
                'demo_url' => 'https://demo.quizmaster.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@quizmaster.com',
                'admin_demo_password' => 'password123',
                'apk_url' => 'https://example.com/downloads/quizmaster-v1.2.apk',
                'thumbnail' => 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=1200&q=80',
                'tech_stack' => ['Flutter', 'Laravel 12', 'Reverb WebSockets', 'Redis Leaderboards', 'Tailwind CSS'],
                'features' => ['Multiplayer live room sync via WebSockets', 'Real-time leaderboard position updates', 'Timed question countdown animations', 'Android APK ready for deployment'],
                'is_featured' => false,
                'is_active' => true,
            ],

            // =========================================================================
            // 7. HEALTHCARE, CLINIC & ERP
            // =========================================================================
            [
                'title' => 'DocTime — Clinic Appointment & Patient EMR System',
                'slug' => 'doctime-clinic-appointment-emr',
                'type' => 'web_app',
                'category' => 'Healthcare & Medical',
                'price' => 1150.00,
                'short_description' => 'Doctor scheduling and electronic medical records software with online appointment booking, SMS reminders, and billing receipts.',
                'description' => 'Manage multi-specialty clinics effortlessly. Features doctor time-slot management, digital patient case files, prescription templates, lab test tracking, and invoice printing.',
                'demo_url' => 'https://demo.doctime.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@doctime.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=80',
                'tech_stack' => ['Laravel 12', 'Next.js 15', 'Tailwind CSS', 'Twilio SMS', 'MySQL'],
                'features' => ['Real-time doctor calendar slot management', 'Electronic health records (EMR) with attachments', 'Automated SMS appointment confirmations', 'Point of Sale (POS) medicine billing'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'CareSync — Enterprise Hospital Information System (HIS)',
                'slug' => 'caresync-hospital-information-system',
                'type' => 'custom',
                'category' => 'Healthcare ERP',
                'price' => 3200.00,
                'short_description' => 'Enterprise hospital management suite with inpatient bed management, pharmacy inventory, lab diagnostics, and insurance billing.',
                'description' => 'A robust medical ERP system for hospitals. Connects admissions, doctors, operating theaters, pharmacies, and billing desks into a synchronized single source of truth.',
                'demo_url' => 'https://demo.caresync.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@caresync.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=1200&q=80',
                'tech_stack' => ['Laravel 12', 'PostgreSQL', 'Next.js 15', 'Tailwind CSS', 'Docker'],
                'features' => ['Inpatient bed allocation & ward live status', 'Pharmacy stock expiry alerts & barcode scanner', 'Laboratory test report dispatching', 'Role-based access for 100+ hospital staff'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'PharmaCare — Pharmacy Point-of-Sale (POS) & Stock Control',
                'slug' => 'pharmacare-pharmacy-pos-inventory',
                'type' => 'web_app',
                'category' => 'Retail & POS',
                'price' => 650.00,
                'short_description' => 'Fast offline-ready pharmacy POS software with batch expiry alerts, barcode thermal printing, and supplier purchase orders.',
                'description' => 'Speed up medicine sales with instant barcode scanning, generic medicine substitutes search, low-stock notifications, and daily cashier shift reconciliation.',
                'demo_url' => 'https://demo.pharmacare.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@pharmacare.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=1200&q=80',
                'tech_stack' => ['React 19', 'Laravel 12 API', 'Tailwind CSS', 'SQLite/MySQL', 'WebESC/POS'],
                'features' => ['Fast barcode scanning & thermal receipt printing', 'Medicine batch number & expiry date tracking', 'Generic alternative drug suggestions', 'Automated supplier reorder purchase orders'],
                'is_featured' => false,
                'is_active' => true,
            ],

            // =========================================================================
            // 8. ENTERPRISE SUITES & CUSTOM ARCHITECTURES
            // =========================================================================
            [
                'title' => 'OmniHotel — Multi-Branch Hospitality & Reservation ERP',
                'slug' => 'omnihotel-multi-branch-hospitality-erp',
                'type' => 'custom',
                'category' => 'Hospitality & Travel',
                'price' => 2400.00,
                'short_description' => 'Multi-property hotel management system with room inventory channels, guest check-in desk, housekeeping telemetry, and billing.',
                'description' => 'Full-stack hospitality microservice. Handles booking engine integrations, housekeeping shift assignments, guest folio invoices, and amenity add-ons across multiple hotel branches.',
                'demo_url' => 'https://demo.omnihotel.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@omnihotel.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80',
                'tech_stack' => ['Laravel 12 Microservice', 'Next.js 15', 'Tailwind CSS', 'Stripe', 'Reverb WebSockets'],
                'features' => ['Multi-branch room inventory synchronization', 'Housekeeping clean/dirty room live status', 'Guest digital check-in and keyless access', 'Automated tax & seasonal rate calculation'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'RestoSync — Restaurant POS, Kitchen Display & QR Menu',
                'slug' => 'restosync-restaurant-pos-kitchen-display',
                'type' => 'custom',
                'category' => 'Hospitality & Food',
                'price' => 1100.00,
                'short_description' => 'Touchscreen restaurant POS with contactless QR table ordering, kitchen display system (KDS), and inventory waste tracking.',
                'description' => 'Modernize dining experiences. Guests scan table QR codes to order and pay, while kitchen staff receive live order tickets on KDS screens with cooking countdown timers.',
                'demo_url' => 'https://demo.restosync.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@restosync.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=1200&q=80',
                'tech_stack' => ['React 19', 'Laravel 12', 'Reverb WebSockets', 'Tailwind CSS', 'Pusher'],
                'features' => ['Contactless QR code digital table menu & payment', 'Real-time Kitchen Display System (KDS) screen', 'Table layout manager with visual seat status', 'Recipe ingredient deduction from stock'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'NexusHR — Enterprise HRMS & Payroll Management Suite',
                'slug' => 'nexushr-enterprise-hrms-payroll',
                'type' => 'web_app',
                'category' => 'Human Resources',
                'price' => 1350.00,
                'short_description' => 'Human resources management software with biometric attendance, payroll calculation, leave approvals, and employee self-service.',
                'description' => 'Automate HR workflows. Features one-click monthly payroll generation with tax deductions, employee leave request workflows, performance reviews, and organizational hierarchy trees.',
                'demo_url' => 'https://demo.nexushr.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@nexushr.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1200&q=80',
                'tech_stack' => ['Laravel 12', 'Next.js 15', 'Tailwind CSS', 'MySQL', 'PDF Salary Slips'],
                'features' => ['Automated payslip PDF generation & email dispatch', 'Multi-tier leave approval management', 'Biometric device attendance sync via API', 'Employee self-service portal & document requests'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'AdPulse — Programmatic Digital Ad Campaign & Click Tracker',
                'slug' => 'adpulse-ad-campaign-click-tracker',
                'type' => 'custom',
                'category' => 'Marketing & Analytics',
                'price' => 1500.00,
                'short_description' => 'High-throughput click tracking and affiliate attribution platform processing 10k+ requests/sec with anti-fraud bot filtering.',
                'description' => 'Track affiliate clicks, conversions, and ad campaign ROI with precision. Includes smart traffic redirect rotators, postback URL dispatching, and fraud detection algorithms.',
                'demo_url' => 'https://demo.adpulse.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@adpulse.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1533750516457-a7f992034fec?w=1200&q=80',
                'tech_stack' => ['Golang Engine', 'Laravel 12 Management API', 'Redis', 'ClickHouse', 'Next.js 15'],
                'features' => ['Sub-10ms URL click redirection engine', 'Real-time postback and conversion webhook firing', 'Anti-fraud proxy and bot IP filtering', 'Affiliate payout balances & invoice generator'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'CryptoPay — Non-Custodial Crypto Payment Gateway for Merchants',
                'slug' => 'cryptopay-merchant-payment-gateway',
                'type' => 'custom',
                'category' => 'Fintech & Web3',
                'price' => 1850.00,
                'short_description' => 'Accept Bitcoin, USDT, and Ethereum payments directly to your cold wallets with zero middleman fees and instant webhooks.',
                'description' => 'A decentralized self-hosted crypto payment gateway. Generates unique payment addresses for every checkout, monitors blockchain transactions, and fires instant IPN webhooks upon confirmation.',
                'demo_url' => 'https://demo.cryptopay.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@cryptopay.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=1200&q=80',
                'tech_stack' => ['Laravel 12 Microservice', 'Web3.php', 'Next.js 15', 'PostgreSQL', 'Redis'],
                'features' => ['Direct-to-wallet non-custodial settlements', 'Dynamic QR codes with exact cryptocurrency amounts', 'Multi-blockchain support (BTC, ETH, TRON, BSC, Polygon)', 'Merchant API keys, plugins & webhook verification'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'LearnFlow — Microlearning & Corporate Training Mobile App',
                'slug' => 'learnflow-corporate-microlearning-app',
                'type' => 'ios',
                'category' => 'EdTech & Corporate',
                'price' => 850.00,
                'short_description' => 'Bite-sized mobile employee onboarding and safety training app with gamified flashcards and compliance quizzes.',
                'description' => 'Engage enterprise employees with 5-minute daily micro-lessons, compliance training streak rewards, and team leaderboards.',
                'demo_url' => 'https://demo.learnflow.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@learnflow.com',
                'admin_demo_password' => 'password123',
                'testflight_url' => 'https://testflight.apple.com/join/demo-learnflow',
                'thumbnail' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80',
                'tech_stack' => ['React Native', 'Laravel 12 API', 'Tailwind CSS', 'AWS S3', 'FCM'],
                'features' => ['Daily micro-learning streak & achievement badges', 'Offline course downloads for remote employees', 'Manager compliance completion tracking dashboard', 'iOS TestFlight ready'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'EventPass — QR Ticket Booking & Gate Scanning Suite',
                'slug' => 'eventpass-qr-ticket-booking-suite',
                'type' => 'android',
                'category' => 'Events & Entertainment',
                'price' => 990.00,
                'short_description' => 'Concert and conference ticketing platform with tiered seating charts, QR admission gate scanners, and Stripe payments.',
                'description' => 'Sell event tickets online with dynamic seat picking. Gate staff use the companion Android scanner app to validate QR codes in under 0.5 seconds with offline fraud protection.',
                'demo_url' => 'https://demo.eventpass.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@eventpass.com',
                'admin_demo_password' => 'password123',
                'apk_url' => 'https://example.com/downloads/eventpass-gate-scanner.apk',
                'thumbnail' => 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&q=80',
                'tech_stack' => ['Flutter', 'Next.js 15', 'Laravel 12', 'Stripe', 'ZBar QR Engine'],
                'features' => ['Interactive visual venue seating chart selector', 'Sub-second QR gate scanner companion app', 'PDF ticket with anti-duplication cryptographic code', 'Real-time gate attendance stats via Reverb'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'GymDesk — Fitness Club Membership & Turnstile Access System',
                'slug' => 'gymdesk-fitness-membership-turnstile',
                'type' => 'web_app',
                'category' => 'Fitness & Sports',
                'price' => 780.00,
                'short_description' => 'Gym management software with RFID/QR turnstile gate integration, personal trainer bookings, and recurring member dues.',
                'description' => 'Streamline gym front-desk operations. Includes automated recurring monthly dues, trainer calendar bookings, locker rentals, and hardware turnstile gate check-in APIs.',
                'demo_url' => 'https://demo.gymdesk.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@gymdesk.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80',
                'tech_stack' => ['Laravel 12', 'Next.js 15', 'Tailwind CSS', 'Stripe Billing', 'RFID Hardware API'],
                'features' => ['RFID card & QR mobile turnstile gate access', 'Automated recurring monthly dues charging', 'Trainer 1-on-1 private session scheduling', 'Member attendance logs & inactive member alerts'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'LegalCase — Law Firm Practice Management & Time Billing',
                'slug' => 'legalcase-law-firm-management',
                'type' => 'web_app',
                'category' => 'Legal & Professional',
                'price' => 1250.00,
                'short_description' => 'Law firm case management system with billable hour stopwatch timers, trust accounting, court calendar deadlines, and client portals.',
                'description' => 'Tailored for attorneys and law practices. Features matter management, conflict of interest checking, IOLTA trust account ledgers, and secure client document exchange rooms.',
                'demo_url' => 'https://demo.legalcase.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@legalcase.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&q=80',
                'tech_stack' => ['Next.js 15', 'Laravel 12', 'PostgreSQL', 'Tailwind CSS', 'PDF Invoice Engine'],
                'features' => ['One-click billable hour stopwatch with rate cards', 'IOLTA compliant trust accounting ledger', 'Court deadline calendar with automatic reminder alerts', 'Encrypted client document sharing room'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'CleanSweep — Home Cleaning & Maid Service Booking App',
                'slug' => 'cleansweep-home-cleaning-booking-app',
                'type' => 'android',
                'category' => 'On-Demand Services',
                'price' => 890.00,
                'short_description' => 'On-demand residential cleaning booking app with dynamic room price calculator, maid GPS tracking, and card payments.',
                'description' => 'Customers select bedroom/bathroom count, choose recurring cleaning schedules, and track their assigned cleaner in real-time. Includes cleaner shift checklist verification and tip payments.',
                'demo_url' => 'https://demo.cleansweep.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@cleansweep.com',
                'admin_demo_password' => 'password123',
                'apk_url' => 'https://example.com/downloads/cleansweep-app.apk',
                'thumbnail' => 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&q=80',
                'tech_stack' => ['Flutter', 'Laravel 12 API', 'Stripe', 'Google Maps SDK', 'FCM'],
                'features' => ['Instant bedroom/bathroom pricing calculator', 'Cleaner live geolocation arrival tracking', 'Recurring weekly/bi-weekly booking discounts', 'In-app tipping & cleaner rating system'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'StockFlow — Warehouse Inventory & Barcode Fulfillment ERP',
                'slug' => 'stockflow-warehouse-inventory-erp',
                'type' => 'custom',
                'category' => 'Supply Chain & ERP',
                'price' => 1950.00,
                'short_description' => 'Warehouse management system with bin location mapping, handheld laser barcode picking, purchase orders, and stock reordering.',
                'description' => 'Optimize multi-warehouse fulfillment. Features bin/aisle location routing for warehouse pickers, automated low-stock supplier purchase orders, and serial number lot tracking.',
                'demo_url' => 'https://demo.stockflow.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@stockflow.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1586528116493-a029325540fa?w=1200&q=80',
                'tech_stack' => ['Laravel 12', 'Next.js 15', 'MySQL', 'Tailwind CSS', 'Zebra Scanner SDK'],
                'features' => ['Warehouse 2D bin & aisle visual map routing', 'Handheld laser barcode scanning & pick lists', 'Automated supplier reorder purchase orders', 'Multi-warehouse inter-transfer tracking'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'FeedVibe — AI Social Media Scheduler & Analytics Hub',
                'slug' => 'feedvibe-social-media-scheduler',
                'type' => 'web_app',
                'category' => 'Marketing & Social',
                'price' => 620.00,
                'short_description' => 'Unified social media publisher for Facebook, Instagram, LinkedIn, and X with AI caption generation and visual calendar planning.',
                'description' => 'Schedule months of social media content in minutes. Features visual drag-and-drop calendar scheduling, AI hashtag and caption generator, multi-account analytics, and team approval workflows.',
                'demo_url' => 'https://demo.feedvibe.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@feedvibe.com',
                'admin_demo_password' => 'password123',
                'thumbnail' => 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&q=80',
                'tech_stack' => ['Next.js 15', 'Laravel 12 API', 'OpenAI', 'Tailwind CSS', 'Social Graph APIs'],
                'features' => ['Visual drag-and-drop multi-channel content calendar', 'AI caption & trending hashtag generator', 'Best time to post algorithmic recommendations', 'Team post approval & review workflows'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'FinTrack — Personal Wealth & Net Worth Dashboard',
                'slug' => 'fintrack-personal-wealth-dashboard',
                'type' => 'ios',
                'category' => 'Fintech & Personal Finance',
                'price' => 750.00,
                'short_description' => 'Personal financial tracker with bank account sync via Plaid, stock and crypto portfolio monitoring, and budget alerts.',
                'description' => 'Track your complete net worth across bank accounts, investment portfolios, real estate, and crypto holdings. Features automated expense categorization and retirement goal forecasts.',
                'demo_url' => 'https://demo.fintrack.test',
                'admin_demo_url' => 'http://backend_hms.test/admin/login',
                'admin_demo_username' => 'admin@fintrack.com',
                'admin_demo_password' => 'password123',
                'testflight_url' => 'https://testflight.apple.com/join/demo-fintrack',
                'thumbnail' => 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=1200&q=80',
                'tech_stack' => ['React Native', 'Laravel 12', 'Plaid API', 'Tailwind CSS', 'ChartKit'],
                'features' => ['Automated bank transaction synchronization via Plaid', 'Interactive net worth & asset allocation charts', 'Monthly budget category alerts & spending caps', 'iOS TestFlight build available'],
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        // Truncate or Upsert products
        foreach ($products as $item) {
            Product::updateOrCreate(
                ['slug' => $item['slug']],
                $item
            );
        }
    }
}
