name: Deploy project to our office server 2
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.thewarriors.team
          username: thewarriors@robertcravat.thewarriors.team
          password: jtgAl[Kt31ld7_Ro
          port: 21
          exclude: |
            **/.git*
            **/.git*/**
            **/dist/**
            dist/**